// Build orchestrator. Runs hourly in CI (and locally):
//  1. fetch + normalize NWS data  -> site/data/forecast.json
//  2. assemble the zero-dep widget -> site/embed.js
//  3. render static PNG images     -> site/images/*.png
//  4. copy fonts + demo page       -> site/
// Only step 1 touches weather.gov, so the gov API sees ~3 requests/hour total.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { fetchWeatherWithFallback } from '../src/lib/weather.mjs';
import { dayCardSvg, hourlyStripSvg, currentSvg, badgeSvg, alertsSvg, ogSvg } from '../src/lib/svg-render.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SITE = path.join(ROOT, 'site');
const args = new Set(process.argv.slice(2));
const skipImages = args.has('--skip-images');
const p = (...s) => path.join(ROOT, ...s);

function ensure(dir) { fs.mkdirSync(dir, { recursive: true }); }
function log(...m) { console.log('[build]', ...m); }

const config = JSON.parse(fs.readFileSync(p('config.json'), 'utf8'));

// ---- Fresh site dir (tolerate filesystems that block recursive unlink)
try { fs.rmSync(SITE, { recursive: true, force: true }); } catch (e) { log('note: could not fully clear site/, overwriting in place'); }
ensure(path.join(SITE, 'data'));
ensure(path.join(SITE, 'images'));
ensure(path.join(SITE, 'fonts'));

// ---- 1. Weather data
log('fetching NWS forecast for', config.location.shortName);
const data = await fetchWeatherWithFallback(config);
if (data.stale) log('WARNING: NWS unavailable — published last-good data (stale)');
fs.writeFileSync(path.join(SITE, 'data', 'forecast.json'), JSON.stringify(data));
fs.writeFileSync(path.join(SITE, 'data', 'forecast.pretty.json'), JSON.stringify(data, null, 2));
log('current', data.current.temp + '°', data.current.condition, '| days', data.days.length, '| hours', data.hourly.length);

// ---- 2. Assemble widget (single source of truth: brand.mjs + icons.mjs + embed-core.js)
const strip = (f, re) => fs.readFileSync(p(f), 'utf8').replace(re, '');
const brand = strip('src/lib/brand.mjs', /^export\s+/gm);
const icons = fs.readFileSync(p('src/lib/icons.mjs'), 'utf8')
  .replace(/^import[^\n]*\n/gm, '')
  .replace(/^export\s+/gm, '');
const core = fs.readFileSync(p('src/embed-core.js'), 'utf8');
const embed =
  '/* Medora Weather widget — generated by build.mjs. Do not edit directly. */\n' +
  '(function(){\n"use strict";\n' +
  'var MW_DEFAULT_BASE=' + JSON.stringify(config.site.baseUrl) + ';\n' +
  'var MW_DEFAULT_LINK=' + JSON.stringify(config.site.fullForecastUrl || '') + ';\n' +
  brand + '\n' + icons + '\n' + core + '\n})();\n';
fs.writeFileSync(path.join(SITE, 'embed.js'), embed);
log('wrote embed.js (' + (embed.length / 1024).toFixed(1) + ' kB)');

// ---- 3. Fonts (served for the widget + used by resvg for images)
for (const f of fs.readdirSync(p('assets/fonts'))) {
  fs.copyFileSync(p('assets/fonts', f), path.join(SITE, 'fonts', f));
}

// ---- 4. Static images
if (!skipImages) {
  const { Resvg } = await import('@resvg/resvg-js');
  const fontFiles = fs.readdirSync(p('assets/fonts'))
    .filter((f) => /\.otf$/i.test(f))
    .map((f) => p('assets/fonts', f));

  const toPng = (svg, scale = 2) => {
    const r = new Resvg(svg, {
      background: 'white',
      fitTo: { mode: 'zoom', value: scale },
      font: { fontFiles, loadSystemFonts: false, defaultFontFamily: 'ITC Clearface Std' }
    });
    return r.render().asPng();
  };

  const jobs = [
    ['forecast-3day.png', dayCardSvg(data, { days: 3 })],
    ['forecast-5day.png', dayCardSvg(data, { days: 5 })],
    ['forecast-7day.png', dayCardSvg(data, { days: 7 })],
    ['hourly.png', hourlyStripSvg(data, { hours: 12 })],
    ['current.png', currentSvg(data)],
    ['badge.png', badgeSvg(data)],
    ['badge-bare.png', badgeSvg(data, { bare: true })],
    ['alert.png', alertsSvg(data)],
    ['social.png', ogSvg(data, { days: 3 })]
  ];
  for (const [name, svg] of jobs) {
    fs.writeFileSync(path.join(SITE, 'images', name), toPng(svg));
    fs.writeFileSync(path.join(SITE, 'images', name.replace(/\.png$/, '.svg')), svg);
    log('rendered', name);
  }
}

// ---- 5. Demo page + assets from public/ (templating __BASE__ in .html files)
if (fs.existsSync(p('public'))) {
  for (const f of fs.readdirSync(p('public'))) {
    const src = p('public', f);
    if (!fs.statSync(src).isFile()) continue;
    if (/\.html$/i.test(f)) {
      const html = fs.readFileSync(src, 'utf8').replaceAll('__BASE__', config.site.baseUrl);
      fs.writeFileSync(path.join(SITE, f), html);
    } else {
      fs.copyFileSync(src, path.join(SITE, f));
    }
  }
}
// .nojekyll so GitHub Pages serves /fonts and dotfiles untouched
fs.writeFileSync(path.join(SITE, '.nojekyll'), '');
// CNAME for the GitHub Pages custom domain (Actions-artifact deploys need it in the artifact)
if (config.site.customDomain) fs.writeFileSync(path.join(SITE, 'CNAME'), config.site.customDomain + '\n');
fs.writeFileSync(path.join(SITE, 'data', 'meta.json'), JSON.stringify({
  generatedAt: data.generatedAt, location: data.location, refreshMinutes: config.cache.refreshMinutes
}, null, 2));

log('done ->', SITE);
